### ISSUE TITLE
Storage `store`

### ISSUE THREAD

**Issue by amimart** [axone-protocol/axone-sdk#4]
Implement the `store` action of the storage provider.

## Details

The `storage.Proxy` allowing the implementation of a custom storage provider shall provide a base implementation of the `store` action that will ensure the requested resource's governance allows the action before calling the specific implementation.

To do so the requested resource's governance have to be retrieved through the dataverse and then queried.

The implementation should return, as a result, [DigitalResourcePublicationCredential](https://github.com/axone-protocol/ontology/blob/main/docs/schemas/credential-digital-resource-publication.md) signed using the managed service's key. It'll be the responsibility of the caller to submit it to the dataverse.

The corresponding http endpoint shall be implemented as well.

**Comment by bdeneux** [comment]
@amimart This one has been issued by #24 no ? I think we can close it ?

**Comment by amimart** [comment]
@bdeneux You are right! Closing it :)
